site_name: ETL Kitchen Book
site_url: https://etl-kitchen-book.ru
edit_uri: ""                # скрыли "Редактировать страницу"
use_directory_urls: true

theme:
  name: material
  language: ru
  logo: assets/logo.svg     # положим позже (можно пустую заглушку)
  favicon: assets/favicon.png
  font:
    text: Inter             # читабельный текст
    code: JetBrains Mono    # шрифт для кода
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    #- navigation.expand
    - header.autohide
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - header.social  
  palette:
    # Авто (следовать системе)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Как в системе
    # Светлая
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    # Тёмная
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Светлая тема

plugins:
  - search
  - roamlinks
  - glightbox

markdown_extensions:
  # Базовые полезности
  - admonition                  # блоки-примочки: !!! tip / note / warning
  - tables                      # таблицы в стиле GitHub
  - footnotes                   # сноски [^1]
  - attr_list                   # классы и атрибуты у элементов { .md-button }
  - md_in_html                  # markdown внутри HTML (для сеток/карточек)
  - toc:
      permalink: true           # якорь “¶” у заголовков

  # Подсветка кода — мощно
  - pymdownx.highlight:
      anchor_linenums: true     # якоря на строках (типа #L12)
      line_spans: __span        # обёртка строк — нужна для подсветки конкретных строк
      pygments_lang_class: true # CSS-класс языка для темы подсветки
      auto_title: true  
  - pymdownx.inlinehilite       # подсветка ИНЛАЙН-кода с указанием языка
  - pymdownx.superfences        # корректные ```блоки``` внутри списков/вкладок
  - pymdownx.details # сворачиваемый блок

  # Вкладки и эмодзи (как было)
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: simple/telegram
      link: https://t.me/etl_kitchen
      name: Telegram

extra_css:
  - styles/extra.css         # добавим ниже


nav:
  - Главная: index.md
  - Инженерия данных:
      - Содержимое раздела: data/index.md
      - Airflow: 
          - Содержимое раздела: data/Airflow/index.md
          - Старт за 15 минут: data/Airflow/start_15_min.md
      - Docker:
          - Содержимое раздела: data/Docker/index.md
          - Portainer: data/Docker/portainer.md
      - Database:
        - Содержимое раздела: data/Database/index.md
        - PostgreSQL & Greenplum: 
          - data/Database/Postgresql_Greenplum/index.md
          - Как читать план запроса: data/Database/Postgresql_Greenplum/query_plan.md
      - Проекты:
        - Содержимое раздела: data/projects/index.md
        - Базовый минимум: data/projects/basic_minimum.md
  - Кулинария:
      - Обзор: cooking/index.md
      - Десерты:
          - Обзор: cooking/dessert/index.md
          - Наполеон: cooking/dessert/napoleon.md
      - Духовка: cooking/oven/index.md
  - Контакты: about/contact.md


extra_javascript:
  - javascripts/header-title-link.js

