site_name: ETL Kitchen Book
site_url: https://etl-kitchen-book.ru
edit_uri: ""                # скрыли "Редактировать страницу"
use_directory_urls: true

theme:
  name: material
  language: ru
  logo: assets/logo.svg     # положим позже (можно пустую заглушку)
  favicon: assets/favicon.png
  font:
    text: Inter             # читабельный текст
    code: JetBrains Mono    # шрифт для кода
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - header.autohide
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - header.social  
  palette:
    # Авто (следовать системе)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Как в системе
    # Светлая
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Тёмная тема
    # Тёмная
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Светлая тема

plugins:
  - search
  - roamlinks
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/etl_kitchen
      name: Telegram

extra_css:
  - styles/extra.css         # добавим ниже


nav:
  - Главная: index.md
  - Инженерия данных:
      - Обзор: data/index.md
      - Airflow:
          - Старт за 15 минут: data/Airflow/start_15_min.md
      - Docker:
          - data/Docker/how_to_load.md
          - data/Docker/start_docker.md
          - data/Docker/new_post.md
      - Database:
          - data/Database/first_t.md
          - Potsgesql:
            - data/Database/Postgresql/frr.md
  - Кулинария:
      - Обзор: cooking/index.md
      - Десерты:
          - Обзор: cooking/dessert/index.md
          - Наполеон: cooking/dessert/napoleon.md
      - Духовка: cooking/oven/index.md
  - Контакты: about/contact.md




